#!/usr/bin/env bash

set -euo pipefail

sum="$(sha256sum /etc/nftables.d/filter-forward-docker.nft 2>/dev/null || echo -n)"

interfaces=""
for gateway in $(docker network ls --format json \
                 | jq -r '.ID' \
                 | xargs docker inspect \
                 | jq -r '.[] | select(.Driver == "bridge") | .IPAM.Config[].Gateway'); do
    if [ "${gateway}" = "null" ]; then
      continue
    fi

    interface="$(ip --brief address show | grep "${gateway}" | awk '{ print $1 }')"

    interfaces="${interfaces} ${interface}"
done

for interface in ${interfaces}; do
    echo "meta iif ${interface} meta oif ${interface} accept"
done | sort -u > /etc/nftables.d/filter-forward-docker.nft

if [ "$(sha256sum /etc/nftables.d/filter-forward-docker.nft)" != "${sum}" ]; then
    systemctl reload nftables.service
fi
