export EDITOR=vim
export SUDO_EDITOR=vim

export HISTFILE=~/.zsh_history
export HISTSIZE=1000000000
export SAVEHIST=100000000
setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


alias ls="ls --color=auto -F -h"
alias ll="ls -l"
alias l="ll"
alias la="ls -la"
alias lla="ls -la"
alias upgradable="apt update && apt list --upgradable"
alias ip="ip -c"
alias d="docker"
alias dc="docker-compose"

autoload -U compinit colors && compinit && colors

zstyle ':completion:*:default' list-colors ""

PROMPT="[%n@%m %~] # "
RPROMPT=""


# Fix keyboard

bindkey -e
case $TERM in (rxvt*) #urxvt
  bindkey "\e[7~"  beginning-of-line
  bindkey "\e[8~"  end-of-line
esac
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey '^?' backward-delete-char
bindkey "\e[3~" delete-char
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey '[C' forward-word
bindkey '[D' backward-word
