#!/usr/bin/env bash

set -euo pipefail

cell_name="{{ item.cell | default(afs_tokens_cell) }}"
krb5_realm="{{ item.realm | default(item.cell | default(afs_tokens_realm)) | upper }}"

echo "{{ item.password }}" | kinit "{{ item.username }}@${krb5_realm}"
klist -e
aklog -c "${cell_name}" -k "${krb5_realm}"
